fix/main_page
Softocean/landing pull request #30
Opened 2023-08-31 13:24 UTC by Dimitry-prog

fix/main_page

2023-08-31 14:49 UTC, Blackk88 requested changes

2023-08-31 14:49 UTC, Blackk88 commented on src/components/main-page/slider/index.tsx
У swiper есть свои params для Breakpoints, лучше сделать через них.

При текущей реализации кстати у меня в консоле ошибка (серверная)

2023-08-31 14:49 UTC, Blackk88 commented on src/components/main-page/slider/index.tsx
>    React.useEffect(() => {
Давайте в одном стиле импортить {useEffect, useState, useRef} from React. Вообщем удали React. в компоненте

2023-08-31 17:43 UTC, Dimitry-prog commented
переделал

2023-09-01 07:59 UTC, Blackk88 approved these changes

2023-09-01 07:59 UTC, merged